name: Check PR

on:
  push:
    branches:
      - master
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build Android App
        uses: sparkfabrik/android-build-action@v1.0.0
        with:
          project-path: 
          output-path: my-app.apk
